new fullpage('#fullPage', {
    autoScrolling: true,
    fitToSection: false,
    fitToSectionDelay: 300,
    easing: 'easeInOutCubic',
    navigation: true,
    anchors: ['Home', 'Sobre-mi', 'Galeria', 'Contacto'],
    navigationTooltips: ['Home', 'Sobre mi', 'Galería', 'Contacto'],
    showActiveTooltip: false,
    menu: '#menu',
    scrollSpeed: 1000,
    controlArrows: false,
    slidesNavigation: true,
    css3: true,
    easingcss3: 'ease-out',
    loopBottom: true,
    keyboardScrolling: true,
	animateAnchor: true,
    recordHistory: false,
    responsiveWidth: 0,
    responsiveHeight: 0,
});

